# Generated by Django 6.0.5 on 2026-05-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='poster_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
